name: push

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          cd plugins
          git checkout 18a59c35ec2f0ae109ac5d86eecf7c232a69a69b
          cd ..

      - name: Generate content
        run: pelican content

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: output
